create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  submission_type text not null check (submission_type in ('application', 'contact', 'partnership')),
  submitted_at timestamptz not null default now(),
  payload jsonb not null
);

alter table public.submissions enable row level security;

-- No public policies are created. The website server writes with the
-- service-role key, which must only be stored as a server environment variable.
